// Map of tennis player → country flag emoji
export const PLAYER_FLAGS: Record<string, string> = {
  // ATP current
  "Jannik Sinner": "🇮🇹",
  "Carlos Alcaraz": "🇪🇸",
  "Alexander Zverev": "🇩🇪",
  "Taylor Fritz": "🇺🇸",
  "Novak Djokovic": "🇷🇸",
  "Daniil Medvedev": "🇷🇺",
  "Casper Ruud": "🇳🇴",
  "Andrey Rublev": "🇷🇺",
  "Holger Rune": "🇩🇰",
  "Alex de Minaur": "🇦🇺",
  "Grigor Dimitrov": "🇧🇬",
  "Stefanos Tsitsipas": "🇬🇷",
  "Tommy Paul": "🇺🇸",
  "Ben Shelton": "🇺🇸",
  "Frances Tiafoe": "🇺🇸",
  "Hubert Hurkacz": "🇵🇱",
  "Felix Auger-Aliassime": "🇨🇦",
  "Karen Khachanov": "🇷🇺",
  "Lorenzo Musetti": "🇮🇹",
  "Ugo Humbert": "🇫🇷",
  "Sebastian Korda": "🇺🇸",
  "Arthur Fils": "🇫🇷",
  "Jakub Mensik": "🇨🇿",
  "Joao Fonseca": "🇧🇷",
  "Tomas Machac": "🇨🇿",
  "Alejandro Davidovich Fokina": "🇪🇸",
  "Francisco Cerundolo": "🇦🇷",
  "Alex Michelsen": "🇺🇸",
  "Learner Tien": "🇺🇸",
  "Jiri Lehecka": "🇨🇿",
  "Flavio Cobolli": "🇮🇹",
  // British men
  "Jack Draper": "🇬🇧",
  "Cameron Norrie": "🇬🇧",
  "Dan Evans": "🇬🇧",
  "Jacob Fearnley": "🇬🇧",
  "Billy Harris": "🇬🇧",
  "Liam Broady": "🇬🇧",
  "Paul Jubb": "🇬🇧",
  "Neal Skupski": "🇬🇧",
  "Joe Salisbury": "🇬🇧",
  "Henry Patten": "🇬🇧",
  "Julian Cash": "🇬🇧",
  "Lloyd Glasspool": "🇬🇧",
  // ATP Legends
  "Rafael Nadal": "🇪🇸",
  "Roger Federer": "🇨🇭",
  "Andy Murray": "🇬🇧",
  "Stan Wawrinka": "🇨🇭",
  "Pete Sampras": "🇺🇸",
  "Andre Agassi": "🇺🇸",
  "Boris Becker": "🇩🇪",
  "John McEnroe": "🇺🇸",
  "Bjorn Borg": "🇸🇪",
  "Ivan Lendl": "🇨🇿",
  "Stefan Edberg": "🇸🇪",
  "Jimmy Connors": "🇺🇸",
  "Tim Henman": "🇬🇧",
  "Greg Rusedski": "🇬🇧",
  "Fred Perry": "🇬🇧",
  "Marat Safin": "🇷🇺",
  "Lleyton Hewitt": "🇦🇺",
  "Juan Martin del Potro": "🇦🇷",
  "Goran Ivanisevic": "🇭🇷",
  "Pat Rafter": "🇦🇺",

  // WTA current
  "Aryna Sabalenka": "🇧🇾",
  "Iga Świątek": "🇵🇱",
  "Coco Gauff": "🇺🇸",
  "Jessica Pegula": "🇺🇸",
  "Jasmine Paolini": "🇮🇹",
  "Madison Keys": "🇺🇸",
  "Mirra Andreeva": "🇷🇺",
  "Qinwen Zheng": "🇨🇳",
  "Elena Rybakina": "🇰🇿",
  "Emma Navarro": "🇺🇸",
  "Paula Badosa": "🇪🇸",
  "Daria Kasatkina": "🇷🇺",
  "Diana Shnaider": "🇷🇺",
  "Barbora Krejcikova": "🇨🇿",
  "Anna Kalinskaya": "🇷🇺",
  "Beatriz Haddad Maia": "🇧🇷",
  "Donna Vekic": "🇭🇷",
  "Karolina Muchova": "🇨🇿",
  "Marta Kostyuk": "🇺🇦",
  "Liudmila Samsonova": "🇷🇺",
  "Elina Svitolina": "🇺🇦",
  "Ekaterina Alexandrova": "🇷🇺",
  "Veronika Kudermetova": "🇷🇺",
  "Magdalena Frech": "🇵🇱",
  "Yulia Putintseva": "🇰🇿",
  "Leylah Fernandez": "🇨🇦",
  "Amanda Anisimova": "🇺🇸",
  "Victoria Mboko": "🇨🇦",
  "Iva Jovic": "🇺🇸",
  "Linda Noskova": "🇨🇿",
  // British women
  "Emma Raducanu": "🇬🇧",
  "Katie Boulter": "🇬🇧",
  "Sonay Kartal": "🇬🇧",
  "Francesca Jones": "🇬🇧",
  "Harriet Dart": "🇬🇧",
  "Jodie Burrage": "🇬🇧",
  "Heather Watson": "🇬🇧",
  "Fran Jones": "🇬🇧",
  // WTA legends
  "Serena Williams": "🇺🇸",
  "Venus Williams": "🇺🇸",
  "Maria Sharapova": "🇷🇺",
  "Naomi Osaka": "🇯🇵",
  "Simona Halep": "🇷🇴",
  "Ash Barty": "🇦🇺",
  "Angelique Kerber": "🇩🇪",
  "Caroline Wozniacki": "🇩🇰",
  "Victoria Azarenka": "🇧🇾",
  "Petra Kvitova": "🇨🇿",
  "Garbine Muguruza": "🇪🇸",
  "Li Na": "🇨🇳",
  "Justine Henin": "🇧🇪",
  "Kim Clijsters": "🇧🇪",
  "Martina Hingis": "🇨🇭",
  "Lindsay Davenport": "🇺🇸",
  "Jennifer Capriati": "🇺🇸",
  "Martina Navratilova": "🇺🇸",
  "Chris Evert": "🇺🇸",
  "Steffi Graf": "🇩🇪",
  "Billie Jean King": "🇺🇸",
  "Monica Seles": "🇺🇸",
  "Margaret Court": "🇦🇺",
  "Virginia Wade": "🇬🇧",
  "Sue Barker": "🇬🇧",
  "Jo Durie": "🇬🇧",

  // Wheelchair
  "Alfie Hewett": "🇬🇧",
  "Gordon Reid": "🇬🇧",
  "Lucy Shuker": "🇬🇧",
  "Andy Lapthorne": "🇬🇧",
  "Gustavo Fernandez": "🇦🇷",
  "Tokito Oda": "🇯🇵",
  "Shingo Kunieda": "🇯🇵",
  "Diede de Groot": "🇳🇱",
  "Aniek van Koot": "🇳🇱",
  "Jiske Griffioen": "🇳🇱",
};

export const getPlayerFlag = (name: string): string | undefined => PLAYER_FLAGS[name];
